### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by EatonZ** [Microsoft/IIS.Compression#15]
I am getting some crashes when some extra compression settings are set. I literally only have a 1-line HTML file on the site and it crashes while trying to process it. It's not trying to process some complex file or anything.
```
<scheme name="br" dll="%ProgramFiles%\IIS\IIS Compression\iisbrotli.dll" dynamicCompressionLevel="10" staticCompressionLevel="10" />
<scheme name="gzip" dll="%ProgramFiles%\IIS\IIS Compression\iiszlib.dll" dynamicCompressionLevel="10" staticCompressionLevel="10" />
```

Here is what shows in Event Viewer:
```
Faulting application name: w3wp.exe, version: 10.0.14393.0, time stamp: 0x57899b8a
Faulting module name: iiszlib.dll, version: 1.0.9.0, time stamp: 0x5af2408d
Exception code: 0xc0000005
Fault offset: 0x00000000000025bb
Faulting process id: 0xeb8
Faulting application start time: 0x01d4376e563981e7
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\Program Files\IIS\IIS Compression\iiszlib.dll
Report Id: 6482ddcb-7c2d-4fba-8480-ee1a07381949
Faulting package full name: 
Faulting package-relative application ID: 
```

And here is what is shown in FREB:
![capture](https://user-images.githubusercontent.com/3020941/44305371-97388480-a343-11e8-98f5-0c060c7187c1.PNG)

**Comment by shirhatti** [comment]
@EatonZ 10 is not a valid compression level for the `iiszlib.dll` provider.
See the docs at https://docs.microsoft.com/en-us/iis/extensions/iis-compression/using-iis-compression#compression-level

cc @bangbingsyb

**Comment by EatonZ** [comment]
@bangbingsyb Can the module write to the Event Viewer? A simple message there like "Compression level out of bounds." would be helpful and shouldn't involve any big IIS changes. I get messages from ASP.NET that say "A potentially dangerous Request.Path value was detected from the client" in the Event Viewer, so this seems like a reasonable thing to add.

**Comment by bangbingsyb** [comment]
@EatonZ I like this idea :) Will try to implement it. Thanks for the suggestion again.

**Comment by bangbingsyb** [comment]
Resolved by https://github.com/Microsoft/IIS.Compression/pull/17

**Comment by EatonZ** [comment]
@bangbingsyb Thank you for a great-looking fix!
When will updated installers be available?

**Comment by bangbingsyb** [comment]
@EatonZ Will work on it this week, and we will have a new release.

**Comment by EatonZ** [comment]
@bangbingsyb Let me know when the new installer is available.

**Comment by bangbingsyb** [comment]
@EatonZ Sure. Sorry for the delay. I completed the installer update last week in our internal repository, and basically all necessary code changes for the new release have been in place. I need to make some minor fix to our build definition before the release. I'm having a tight schedule last and this week for other tasks. Will keep you updated once the installer is ready.

**Comment by EatonZ** [comment]
@bangbingsyb Is the new version available yet?

**Comment by EatonZ** [comment]
@bangbingsyb Checking in again ^

**Comment by EatonZ** [comment]
@bangbingsyb @shirhatti Did you decide against publishing an update for this?

**Comment by bangbingsyb** [comment]
@EatonZ sorry for the long delay. I was switched out to other tasks and we also had infrastructure changes during the period. Now I've moved all the installer pieces to the same repository, and will work on a new release soon.

**Comment by bangbingsyb** [comment]
@EatonZ The new release (v1.0.3219) has been published and is available through the same download link. The issue has been fixed in the new release - both iiszlib and iisbrotli auto-adjust the out-of-bound compression level to the maximum allowed value and produce a warning to event log (but only emit a single warning event per worker process life time).

**Comment by EatonZ** [comment]
@bangbingsyb Great - thanks!
