### ISSUE TITLE
Support to Azure Web Apps (or confirm compiled binary redistribution license)

### ISSUE THREAD

**Issue by shibayan** [Microsoft/IIS.Compression#16]
@shirhatti 

I would like to make this exciting module available for Azure Web Apps. I can not install msi with Web Apps, but I can distribute dll with the mechanism called "Site Extension".

I can also create Site Extension. However, regarding redistribution of the compiled binary, I need to confirm if the license is OK.

**Comment by shirhatti** [comment]
I am not a lawyer, so I cannot speak definitively.

But based on my understanding the MIT license is certainly permissive enough. Just make include a third party notices file that includes our license, as well as our dependent licenses contained in our thirdpartynotices file.

**Comment by shirhatti** [comment]
I was going to point you at https://github.com/shibayan/IISManager for help with site extensions, but I just realized you are the author 😄. Love the good work you're doing!

**Comment by bangbingsyb** [comment]
@shibayan Awesome! Appreciate your interest and efforts of making IIS Compression available for Azure Web Apps through site extension. This is something we want to push since the beginning, but was somehow delayed. Thanks!

**Comment by shibayan** [comment]
@bangbingsyb Thank you. I'm automating the creation of Site Extension with the following repository.
https://github.com/shibayan/IIS.Compression.SiteExtension

**Comment by bariscaglar** [comment]
Closing the issue.
