### ISSUE TITLE
Upload the module to Chocolatey

### ISSUE THREAD

**Issue by deyjcode** [microsoft/IIS.Compression#28]
I am not sure if I am able to do this myself to comply with the [legal right to distribute](https://chocolatey.org/docs/legal).

But I would like to be able to have the IIS Compression module available via Chocolatey so I can run modules like the [Ansible Chocolatey module](https://docs.ansible.com/ansible/latest/modules/win_chocolatey_module.html).

**Comment by bangbingsyb** [comment]
Having IIS.Compression available via Chocolatey sounds like a good idea to me.

@shirhatti Could you help figure out the legal compliance?

**Comment by deyjcode** [comment]
Hey guys - just pinging to grab an update on this.

**Comment by shirhatti** [comment]
Thanks for following up! Yes, we welcome a contribution from a community member to maintain and update a chocolatey distribution of IIS Compression.

![](https://user-images.githubusercontent.com/4734691/60459859-0e42d880-9bf7-11e9-808c-d706aae3eb88.png)

In addition, I highly recommend following the repo or at least following releases so you can be notified of new releases of IIS Compression.

**Comment by bangbingsyb** [comment]
@shirhatti What about his concern about "legal right to distribute"?

**Comment by shirhatti** [comment]
Our license is permissive enough to allow you to distribute

**Comment by bangbingsyb** [comment]
Close the issue since we have already provided a clear answer :)

**Comment by deyjcode** [comment]
This has been completed and [is now available from chocolatey](https://chocolatey.org/packages/iis-compression). Verification tests fail on lack of IIS, so I'm working to get those tests exempted.
