### ISSUE TITLE
In what state is this in?

### ISSUE THREAD

**Issue by avieru** [Microsoft/IIS.Compression#9]
Read me didn't quite explain if this is good to run in production or at some point in the future?

Hoping for some clarification and thank you for your efforts with this.

**Comment by bangbingsyb** [comment]
@avieru Thanks for asking!

IIS Compression is in "release pending" state. We expect that the official installer will be available for downloading in the next two weeks. We will also update README and publish docs on https://docs.microsoft.com/en-us/iis/ as well as https://www.iis.net/.

**Comment by bariscaglar** [comment]
I think we are still 2-3 weeks out for the final release. Please keep an eye on https://www.iis.net for the announcement.
